import { jsPDF } from "jspdf";

interface PdfReportInput {
  artworkName: string;
  artistName: string;
  fileName: string;
  analyzedAt: string;
  scoreLine: string;
  predLine: string;
  verdict: string;
  explanation: string;
  /** Base64 data URL of image, optional */
  imageDataUrl?: string;
}

export async function buildAnalysisPdf(input: PdfReportInput): Promise<Blob> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const pageBottom = 275;
  const lineH = 5;
  let y = margin;

  const newPage = () => {
    doc.addPage();
    y = margin;
  };

  const textBlock = (lines: string[], fontSize = 10) => {
    doc.setFontSize(fontSize);
    for (const line of lines) {
      if (y > pageBottom) newPage();
      doc.text(line, margin, y);
      y += lineH;
    }
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("ArtGuard Authenticity Report", margin, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("AI-assisted patch-level analysis — not a certificate of authenticity.", margin, y);
  y += 8;
  doc.setTextColor(0, 0, 0);

  if (input.imageDataUrl?.startsWith("data:image")) {
    try {
      const fmt = input.imageDataUrl.includes("image/png") ? "PNG" : "JPEG";
      const maxW = pageWidth - margin * 2;
      const imgH = 70;
      if (y + imgH > pageBottom) newPage();
      doc.addImage(input.imageDataUrl, fmt, margin, y, maxW, imgH);
      y += imgH + 6;
    } catch {
      y += 4;
    }
  }

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Artwork", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  textBlock(
    [
      `Title: ${input.artworkName}`,
      `Artist: ${input.artistName}`,
      `File: ${input.fileName}`,
      `Analyzed: ${input.analyzedAt}`,
    ],
    10
  );
  y += 4;

  if (y > pageBottom - 20) newPage();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Results", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  textBlock([input.scoreLine, ...(input.predLine ? [input.predLine] : []), `Verdict: ${input.verdict}`]);
  y += 4;

  if (y > pageBottom - 30) newPage();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Method", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const methodLines = doc.splitTextToSize(
    [
      "Inference: Swin Vision Transformer (fine-tuned), patch-level classification on 224×224 px regions.",
      "Aggregation: mean pooling over patch authenticity probabilities.",
      "Explanation: Claude Sonnet via AWS Bedrock, grounded in art-historical retrieval (OpenSearch Serverless).",
    ].join(" "),
    pageWidth - margin * 2
  );
  for (let i = 0; i < methodLines.length; i++) {
    if (y > pageBottom) newPage();
    doc.text(methodLines[i], margin, y);
    y += lineH;
  }
  y += 6;

  if (y > pageBottom - 20) newPage();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Explanation", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const explLines = doc.splitTextToSize(input.explanation || "(none)", pageWidth - margin * 2);
  for (let i = 0; i < explLines.length; i++) {
    if (y > pageBottom) newPage();
    doc.text(explLines[i], margin, y);
    y += lineH;
  }
  y += 8;

  if (y > pageBottom - 24) newPage();
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  const disclaimer = doc.splitTextToSize(
    "This report is generated by machine learning and is not a substitute for professional authentication. Consult certified experts for high-value or legal decisions.",
    pageWidth - margin * 2
  );
  for (let i = 0; i < disclaimer.length; i++) {
    if (y > pageBottom) newPage();
    doc.text(disclaimer[i], margin, y);
    y += 4.5;
  }

  return doc.output("blob");
}
